name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: temurin

    - name: Build with Gradle
      run: ./gradlew build cyclonedxBom

    - name: Combine artifacts
      run: |
        mkdir release
        cp build/libs/* release/
        cp build/reports/cyclonedx/* release/

    - name: Upload Artifacts
      uses: fnkr/github-action-ghr@96b1448dc6162f370067e1de51e856e733a76b4f
      env:
        GHR_PATH: release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
