name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Artifacts
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: build/libs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
